name: Rustc Host Detection

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  detect-host:
    name: Detect Rust Host Triple
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: Linux
          - os: macos-13
            name: macOS x86_64
          - os: macos-latest
            name: macOS ARM64
          - os: windows-latest
            name: Windows

    steps:
      - name: Detect Rust host triple
        run: 'rustc -vV | grep host:'
        shell: bash
